/*
 * Account Management
 * This is Swagger UI environment generated for the TMF Account Management specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BillFormat;
import io.swagger.client.model.BillFormatCreate;
import io.swagger.client.model.BillFormatUpdate;
import io.swagger.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BillFormatApi
 */
@Ignore
public class BillFormatApiTest {

    private final BillFormatApi api = new BillFormatApi();

    
    /**
     * Creates a BillFormat
     *
     * This operation creates a BillFormat entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createBillFormatTest() throws ApiException {
        BillFormatCreate billFormat = null;
        BillFormat response = api.createBillFormat(billFormat);

        // TODO: test validations
    }
    
    /**
     * Deletes a BillFormat
     *
     * This operation deletes a BillFormat entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteBillFormatTest() throws ApiException {
        String id = null;
        api.deleteBillFormat(id);

        // TODO: test validations
    }
    
    /**
     * List or find BillFormat objects
     *
     * This operation list or find BillFormat entities
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listBillFormatTest() throws ApiException {
        String fields = null;
        Integer offset = null;
        Integer limit = null;
        List<BillFormat> response = api.listBillFormat(fields, offset, limit);

        // TODO: test validations
    }
    
    /**
     * Updates partially a BillFormat
     *
     * This operation updates partially a BillFormat entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchBillFormatTest() throws ApiException {
        String id = null;
        BillFormatUpdate billFormat = null;
        BillFormat response = api.patchBillFormat(id, billFormat);

        // TODO: test validations
    }
    
    /**
     * Retrieves a BillFormat by ID
     *
     * This operation retrieves a BillFormat entity. Attribute selection is enabled for all first level attributes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveBillFormatTest() throws ApiException {
        String id = null;
        String fields = null;
        BillFormat response = api.retrieveBillFormat(id, fields);

        // TODO: test validations
    }
    
}
