/*
 * Account Management
 * This is Swagger UI environment generated for the TMF Account Management specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BillingCycleSpecification;
import io.swagger.client.model.BillingCycleSpecificationCreate;
import io.swagger.client.model.BillingCycleSpecificationUpdate;
import io.swagger.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BillingCycleSpecificationApi
 */
@Ignore
public class BillingCycleSpecificationApiTest {

    private final BillingCycleSpecificationApi api = new BillingCycleSpecificationApi();

    
    /**
     * Creates a BillingCycleSpecification
     *
     * This operation creates a BillingCycleSpecification entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createBillingCycleSpecificationTest() throws ApiException {
        BillingCycleSpecificationCreate billingCycleSpecification = null;
        BillingCycleSpecification response = api.createBillingCycleSpecification(billingCycleSpecification);

        // TODO: test validations
    }
    
    /**
     * Deletes a BillingCycleSpecification
     *
     * This operation deletes a BillingCycleSpecification entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteBillingCycleSpecificationTest() throws ApiException {
        String id = null;
        api.deleteBillingCycleSpecification(id);

        // TODO: test validations
    }
    
    /**
     * List or find BillingCycleSpecification objects
     *
     * This operation list or find BillingCycleSpecification entities
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listBillingCycleSpecificationTest() throws ApiException {
        String fields = null;
        Integer offset = null;
        Integer limit = null;
        List<BillingCycleSpecification> response = api.listBillingCycleSpecification(fields, offset, limit);

        // TODO: test validations
    }
    
    /**
     * Updates partially a BillingCycleSpecification
     *
     * This operation updates partially a BillingCycleSpecification entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchBillingCycleSpecificationTest() throws ApiException {
        String id = null;
        BillingCycleSpecificationUpdate billingCycleSpecification = null;
        BillingCycleSpecification response = api.patchBillingCycleSpecification(id, billingCycleSpecification);

        // TODO: test validations
    }
    
    /**
     * Retrieves a BillingCycleSpecification by ID
     *
     * This operation retrieves a BillingCycleSpecification entity. Attribute selection is enabled for all first level attributes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveBillingCycleSpecificationTest() throws ApiException {
        String id = null;
        String fields = null;
        BillingCycleSpecification response = api.retrieveBillingCycleSpecification(id, fields);

        // TODO: test validations
    }
    
}
