/*
 * Account Management
 * This is Swagger UI environment generated for the TMF Account Management specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BillPresentationMedia;
import io.swagger.client.model.BillPresentationMediaCreate;
import io.swagger.client.model.BillPresentationMediaUpdate;
import io.swagger.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BillPresentationMediaApi
 */
@Ignore
public class BillPresentationMediaApiTest {

    private final BillPresentationMediaApi api = new BillPresentationMediaApi();

    
    /**
     * Creates a BillPresentationMedia
     *
     * This operation creates a BillPresentationMedia entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createBillPresentationMediaTest() throws ApiException {
        BillPresentationMediaCreate billPresentationMedia = null;
        BillPresentationMedia response = api.createBillPresentationMedia(billPresentationMedia);

        // TODO: test validations
    }
    
    /**
     * Deletes a BillPresentationMedia
     *
     * This operation deletes a BillPresentationMedia entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteBillPresentationMediaTest() throws ApiException {
        String id = null;
        api.deleteBillPresentationMedia(id);

        // TODO: test validations
    }
    
    /**
     * List or find BillPresentationMedia objects
     *
     * This operation list or find BillPresentationMedia entities
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listBillPresentationMediaTest() throws ApiException {
        String fields = null;
        Integer offset = null;
        Integer limit = null;
        List<BillPresentationMedia> response = api.listBillPresentationMedia(fields, offset, limit);

        // TODO: test validations
    }
    
    /**
     * Updates partially a BillPresentationMedia
     *
     * This operation updates partially a BillPresentationMedia entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchBillPresentationMediaTest() throws ApiException {
        String id = null;
        BillPresentationMediaUpdate billPresentationMedia = null;
        BillPresentationMedia response = api.patchBillPresentationMedia(id, billPresentationMedia);

        // TODO: test validations
    }
    
    /**
     * Retrieves a BillPresentationMedia by ID
     *
     * This operation retrieves a BillPresentationMedia entity. Attribute selection is enabled for all first level attributes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveBillPresentationMediaTest() throws ApiException {
        String id = null;
        String fields = null;
        BillPresentationMedia response = api.retrieveBillPresentationMedia(id, fields);

        // TODO: test validations
    }
    
}
