/*
 * Account Management
 * This is Swagger UI environment generated for the TMF Account Management specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.FinancialAccount;
import io.swagger.client.model.FinancialAccountCreate;
import io.swagger.client.model.FinancialAccountUpdate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FinancialAccountApi
 */
@Ignore
public class FinancialAccountApiTest {

    private final FinancialAccountApi api = new FinancialAccountApi();

    
    /**
     * Creates a FinancialAccount
     *
     * This operation creates a FinancialAccount entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFinancialAccountTest() throws ApiException {
        FinancialAccountCreate financialAccount = null;
        FinancialAccount response = api.createFinancialAccount(financialAccount);

        // TODO: test validations
    }
    
    /**
     * Deletes a FinancialAccount
     *
     * This operation deletes a FinancialAccount entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFinancialAccountTest() throws ApiException {
        String id = null;
        api.deleteFinancialAccount(id);

        // TODO: test validations
    }
    
    /**
     * List or find FinancialAccount objects
     *
     * This operation list or find FinancialAccount entities
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listFinancialAccountTest() throws ApiException {
        String fields = null;
        Integer offset = null;
        Integer limit = null;
        List<FinancialAccount> response = api.listFinancialAccount(fields, offset, limit);

        // TODO: test validations
    }
    
    /**
     * Updates partially a FinancialAccount
     *
     * This operation updates partially a FinancialAccount entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchFinancialAccountTest() throws ApiException {
        String id = null;
        FinancialAccountUpdate financialAccount = null;
        FinancialAccount response = api.patchFinancialAccount(id, financialAccount);

        // TODO: test validations
    }
    
    /**
     * Retrieves a FinancialAccount by ID
     *
     * This operation retrieves a FinancialAccount entity. Attribute selection is enabled for all first level attributes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveFinancialAccountTest() throws ApiException {
        String id = null;
        String fields = null;
        FinancialAccount response = api.retrieveFinancialAccount(id, fields);

        // TODO: test validations
    }
    
}
