/*
 * Account Management
 * This is Swagger UI environment generated for the TMF Account Management specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.BillingAccountAttributeValueChangeEvent;
import io.swagger.client.model.BillingAccountStateChangeEvent;
import io.swagger.client.model.Error;
import io.swagger.client.model.EventSubscription;
import io.swagger.client.model.FinancialAccountAttributeValueChangeEvent;
import io.swagger.client.model.FinancialAccountCreateEvent;
import io.swagger.client.model.FinancialAccountDeleteEvent;
import io.swagger.client.model.FinancialAccountStateChangeEvent;
import io.swagger.client.model.PartyAccountAttributeValueChangeEvent;
import io.swagger.client.model.PartyAccountStateChangeEvent;
import io.swagger.client.model.SettlementAccountAttributeValueChangeEvent;
import io.swagger.client.model.SettlementAccountStateChangeEvent;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NotificationListenersClientSideApi
 */
@Ignore
public class NotificationListenersClientSideApiTest {

    private final NotificationListenersClientSideApi api = new NotificationListenersClientSideApi();

    
    /**
     * Client listener for entity BillingAccountAttributeValueChangeEvent
     *
     * Example of a client listener for receiving the notification BillingAccountAttributeValueChangeEvent
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToBillingAccountAttributeValueChangeEventTest() throws ApiException {
        BillingAccountAttributeValueChangeEvent data = null;
        EventSubscription response = api.listenToBillingAccountAttributeValueChangeEvent(data);

        // TODO: test validations
    }
    
    /**
     * Client listener for entity BillingAccountStateChangeEvent
     *
     * Example of a client listener for receiving the notification BillingAccountStateChangeEvent
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToBillingAccountStateChangeEventTest() throws ApiException {
        BillingAccountStateChangeEvent data = null;
        EventSubscription response = api.listenToBillingAccountStateChangeEvent(data);

        // TODO: test validations
    }
    
    /**
     * Client listener for entity FinancialAccountAttributeValueChangeEvent
     *
     * Example of a client listener for receiving the notification FinancialAccountAttributeValueChangeEvent
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToFinancialAccountAttributeValueChangeEventTest() throws ApiException {
        FinancialAccountAttributeValueChangeEvent data = null;
        EventSubscription response = api.listenToFinancialAccountAttributeValueChangeEvent(data);

        // TODO: test validations
    }
    
    /**
     * Client listener for entity FinancialAccountCreateEvent
     *
     * Example of a client listener for receiving the notification FinancialAccountCreateEvent
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToFinancialAccountCreateEventTest() throws ApiException {
        FinancialAccountCreateEvent data = null;
        EventSubscription response = api.listenToFinancialAccountCreateEvent(data);

        // TODO: test validations
    }
    
    /**
     * Client listener for entity FinancialAccountDeleteEvent
     *
     * Example of a client listener for receiving the notification FinancialAccountDeleteEvent
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToFinancialAccountDeleteEventTest() throws ApiException {
        FinancialAccountDeleteEvent data = null;
        EventSubscription response = api.listenToFinancialAccountDeleteEvent(data);

        // TODO: test validations
    }
    
    /**
     * Client listener for entity FinancialAccountStateChangeEvent
     *
     * Example of a client listener for receiving the notification FinancialAccountStateChangeEvent
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToFinancialAccountStateChangeEventTest() throws ApiException {
        FinancialAccountStateChangeEvent data = null;
        EventSubscription response = api.listenToFinancialAccountStateChangeEvent(data);

        // TODO: test validations
    }
    
    /**
     * Client listener for entity PartyAccountAttributeValueChangeEvent
     *
     * Example of a client listener for receiving the notification PartyAccountAttributeValueChangeEvent
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToPartyAccountAttributeValueChangeEventTest() throws ApiException {
        PartyAccountAttributeValueChangeEvent data = null;
        EventSubscription response = api.listenToPartyAccountAttributeValueChangeEvent(data);

        // TODO: test validations
    }
    
    /**
     * Client listener for entity PartyAccountStateChangeEvent
     *
     * Example of a client listener for receiving the notification PartyAccountStateChangeEvent
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToPartyAccountStateChangeEventTest() throws ApiException {
        PartyAccountStateChangeEvent data = null;
        EventSubscription response = api.listenToPartyAccountStateChangeEvent(data);

        // TODO: test validations
    }
    
    /**
     * Client listener for entity SettlementAccountAttributeValueChangeEvent
     *
     * Example of a client listener for receiving the notification SettlementAccountAttributeValueChangeEvent
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToSettlementAccountAttributeValueChangeEventTest() throws ApiException {
        SettlementAccountAttributeValueChangeEvent data = null;
        EventSubscription response = api.listenToSettlementAccountAttributeValueChangeEvent(data);

        // TODO: test validations
    }
    
    /**
     * Client listener for entity SettlementAccountStateChangeEvent
     *
     * Example of a client listener for receiving the notification SettlementAccountStateChangeEvent
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listenToSettlementAccountStateChangeEventTest() throws ApiException {
        SettlementAccountStateChangeEvent data = null;
        EventSubscription response = api.listenToSettlementAccountStateChangeEvent(data);

        // TODO: test validations
    }
    
}
