/*
 * Account Management
 * This is Swagger UI environment generated for the TMF Account Management specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Error;
import io.swagger.client.model.SettlementAccount;
import io.swagger.client.model.SettlementAccountCreate;
import io.swagger.client.model.SettlementAccountUpdate;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SettlementAccountApi
 */
@Ignore
public class SettlementAccountApiTest {

    private final SettlementAccountApi api = new SettlementAccountApi();

    
    /**
     * Creates a SettlementAccount
     *
     * This operation creates a SettlementAccount entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSettlementAccountTest() throws ApiException {
        SettlementAccountCreate settlementAccount = null;
        SettlementAccount response = api.createSettlementAccount(settlementAccount);

        // TODO: test validations
    }
    
    /**
     * Deletes a SettlementAccount
     *
     * This operation deletes a SettlementAccount entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSettlementAccountTest() throws ApiException {
        String id = null;
        api.deleteSettlementAccount(id);

        // TODO: test validations
    }
    
    /**
     * List or find SettlementAccount objects
     *
     * This operation list or find SettlementAccount entities
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSettlementAccountTest() throws ApiException {
        String fields = null;
        Integer offset = null;
        Integer limit = null;
        List<SettlementAccount> response = api.listSettlementAccount(fields, offset, limit);

        // TODO: test validations
    }
    
    /**
     * Updates partially a SettlementAccount
     *
     * This operation updates partially a SettlementAccount entity.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void patchSettlementAccountTest() throws ApiException {
        String id = null;
        SettlementAccountUpdate settlementAccount = null;
        SettlementAccount response = api.patchSettlementAccount(id, settlementAccount);

        // TODO: test validations
    }
    
    /**
     * Retrieves a SettlementAccount by ID
     *
     * This operation retrieves a SettlementAccount entity. Attribute selection is enabled for all first level attributes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveSettlementAccountTest() throws ApiException {
        String id = null;
        String fields = null;
        SettlementAccount response = api.retrieveSettlementAccount(id, fields);

        // TODO: test validations
    }
    
}
