/*
 * Account Management
 * This is Swagger UI environment generated for the TMF Account Management specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiCallback;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.ApiResponse;
import io.swagger.client.Configuration;
import io.swagger.client.Pair;
import io.swagger.client.ProgressRequestBody;
import io.swagger.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.client.model.BillingCycleSpecification;
import io.swagger.client.model.BillingCycleSpecificationCreate;
import io.swagger.client.model.BillingCycleSpecificationUpdate;
import io.swagger.client.model.Error;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BillingCycleSpecificationApi {
    private ApiClient apiClient;

    public BillingCycleSpecificationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public BillingCycleSpecificationApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for createBillingCycleSpecification
     * @param billingCycleSpecification The BillingCycleSpecification to be created (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call createBillingCycleSpecificationCall(BillingCycleSpecificationCreate billingCycleSpecification, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = billingCycleSpecification;

        // create path and map variables
        String localVarPath = "/billingCycleSpecification";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json;charset=utf-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json;charset=utf-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call createBillingCycleSpecificationValidateBeforeCall(BillingCycleSpecificationCreate billingCycleSpecification, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'billingCycleSpecification' is set
        if (billingCycleSpecification == null) {
            throw new ApiException("Missing the required parameter 'billingCycleSpecification' when calling createBillingCycleSpecification(Async)");
        }
        

        com.squareup.okhttp.Call call = createBillingCycleSpecificationCall(billingCycleSpecification, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Creates a BillingCycleSpecification
     * This operation creates a BillingCycleSpecification entity.
     * @param billingCycleSpecification The BillingCycleSpecification to be created (required)
     * @return BillingCycleSpecification
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public BillingCycleSpecification createBillingCycleSpecification(BillingCycleSpecificationCreate billingCycleSpecification) throws ApiException {
        ApiResponse<BillingCycleSpecification> resp = createBillingCycleSpecificationWithHttpInfo(billingCycleSpecification);
        return resp.getData();
    }

    /**
     * Creates a BillingCycleSpecification
     * This operation creates a BillingCycleSpecification entity.
     * @param billingCycleSpecification The BillingCycleSpecification to be created (required)
     * @return ApiResponse&lt;BillingCycleSpecification&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<BillingCycleSpecification> createBillingCycleSpecificationWithHttpInfo(BillingCycleSpecificationCreate billingCycleSpecification) throws ApiException {
        com.squareup.okhttp.Call call = createBillingCycleSpecificationValidateBeforeCall(billingCycleSpecification, null, null);
        Type localVarReturnType = new TypeToken<BillingCycleSpecification>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Creates a BillingCycleSpecification (asynchronously)
     * This operation creates a BillingCycleSpecification entity.
     * @param billingCycleSpecification The BillingCycleSpecification to be created (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call createBillingCycleSpecificationAsync(BillingCycleSpecificationCreate billingCycleSpecification, final ApiCallback<BillingCycleSpecification> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = createBillingCycleSpecificationValidateBeforeCall(billingCycleSpecification, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<BillingCycleSpecification>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for deleteBillingCycleSpecification
     * @param id Identifier of the BillingCycleSpecification (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call deleteBillingCycleSpecificationCall(String id, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/billingCycleSpecification/{id}"
            .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json;charset=utf-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json;charset=utf-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call deleteBillingCycleSpecificationValidateBeforeCall(String id, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling deleteBillingCycleSpecification(Async)");
        }
        

        com.squareup.okhttp.Call call = deleteBillingCycleSpecificationCall(id, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Deletes a BillingCycleSpecification
     * This operation deletes a BillingCycleSpecification entity.
     * @param id Identifier of the BillingCycleSpecification (required)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public void deleteBillingCycleSpecification(String id) throws ApiException {
        deleteBillingCycleSpecificationWithHttpInfo(id);
    }

    /**
     * Deletes a BillingCycleSpecification
     * This operation deletes a BillingCycleSpecification entity.
     * @param id Identifier of the BillingCycleSpecification (required)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<Void> deleteBillingCycleSpecificationWithHttpInfo(String id) throws ApiException {
        com.squareup.okhttp.Call call = deleteBillingCycleSpecificationValidateBeforeCall(id, null, null);
        return apiClient.execute(call);
    }

    /**
     * Deletes a BillingCycleSpecification (asynchronously)
     * This operation deletes a BillingCycleSpecification entity.
     * @param id Identifier of the BillingCycleSpecification (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call deleteBillingCycleSpecificationAsync(String id, final ApiCallback<Void> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = deleteBillingCycleSpecificationValidateBeforeCall(id, progressListener, progressRequestListener);
        apiClient.executeAsync(call, callback);
        return call;
    }
    /**
     * Build call for listBillingCycleSpecification
     * @param fields Comma-separated properties to be provided in response (optional)
     * @param offset Requested index for start of resources to be provided in response (optional)
     * @param limit Requested number of resources to be provided in response (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call listBillingCycleSpecificationCall(String fields, Integer offset, Integer limit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/billingCycleSpecification";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (fields != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("fields", fields));
        if (offset != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("offset", offset));
        if (limit != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("limit", limit));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json;charset=utf-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json;charset=utf-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call listBillingCycleSpecificationValidateBeforeCall(String fields, Integer offset, Integer limit, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        

        com.squareup.okhttp.Call call = listBillingCycleSpecificationCall(fields, offset, limit, progressListener, progressRequestListener);
        return call;

    }

    /**
     * List or find BillingCycleSpecification objects
     * This operation list or find BillingCycleSpecification entities
     * @param fields Comma-separated properties to be provided in response (optional)
     * @param offset Requested index for start of resources to be provided in response (optional)
     * @param limit Requested number of resources to be provided in response (optional)
     * @return List&lt;BillingCycleSpecification&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<BillingCycleSpecification> listBillingCycleSpecification(String fields, Integer offset, Integer limit) throws ApiException {
        ApiResponse<List<BillingCycleSpecification>> resp = listBillingCycleSpecificationWithHttpInfo(fields, offset, limit);
        return resp.getData();
    }

    /**
     * List or find BillingCycleSpecification objects
     * This operation list or find BillingCycleSpecification entities
     * @param fields Comma-separated properties to be provided in response (optional)
     * @param offset Requested index for start of resources to be provided in response (optional)
     * @param limit Requested number of resources to be provided in response (optional)
     * @return ApiResponse&lt;List&lt;BillingCycleSpecification&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<BillingCycleSpecification>> listBillingCycleSpecificationWithHttpInfo(String fields, Integer offset, Integer limit) throws ApiException {
        com.squareup.okhttp.Call call = listBillingCycleSpecificationValidateBeforeCall(fields, offset, limit, null, null);
        Type localVarReturnType = new TypeToken<List<BillingCycleSpecification>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * List or find BillingCycleSpecification objects (asynchronously)
     * This operation list or find BillingCycleSpecification entities
     * @param fields Comma-separated properties to be provided in response (optional)
     * @param offset Requested index for start of resources to be provided in response (optional)
     * @param limit Requested number of resources to be provided in response (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call listBillingCycleSpecificationAsync(String fields, Integer offset, Integer limit, final ApiCallback<List<BillingCycleSpecification>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = listBillingCycleSpecificationValidateBeforeCall(fields, offset, limit, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<BillingCycleSpecification>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for patchBillingCycleSpecification
     * @param id Identifier of the BillingCycleSpecification (required)
     * @param billingCycleSpecification The BillingCycleSpecification to be updated (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call patchBillingCycleSpecificationCall(String id, BillingCycleSpecificationUpdate billingCycleSpecification, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = billingCycleSpecification;

        // create path and map variables
        String localVarPath = "/billingCycleSpecification/{id}"
            .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json;charset=utf-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json;charset=utf-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call patchBillingCycleSpecificationValidateBeforeCall(String id, BillingCycleSpecificationUpdate billingCycleSpecification, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling patchBillingCycleSpecification(Async)");
        }
        
        // verify the required parameter 'billingCycleSpecification' is set
        if (billingCycleSpecification == null) {
            throw new ApiException("Missing the required parameter 'billingCycleSpecification' when calling patchBillingCycleSpecification(Async)");
        }
        

        com.squareup.okhttp.Call call = patchBillingCycleSpecificationCall(id, billingCycleSpecification, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Updates partially a BillingCycleSpecification
     * This operation updates partially a BillingCycleSpecification entity.
     * @param id Identifier of the BillingCycleSpecification (required)
     * @param billingCycleSpecification The BillingCycleSpecification to be updated (required)
     * @return BillingCycleSpecification
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public BillingCycleSpecification patchBillingCycleSpecification(String id, BillingCycleSpecificationUpdate billingCycleSpecification) throws ApiException {
        ApiResponse<BillingCycleSpecification> resp = patchBillingCycleSpecificationWithHttpInfo(id, billingCycleSpecification);
        return resp.getData();
    }

    /**
     * Updates partially a BillingCycleSpecification
     * This operation updates partially a BillingCycleSpecification entity.
     * @param id Identifier of the BillingCycleSpecification (required)
     * @param billingCycleSpecification The BillingCycleSpecification to be updated (required)
     * @return ApiResponse&lt;BillingCycleSpecification&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<BillingCycleSpecification> patchBillingCycleSpecificationWithHttpInfo(String id, BillingCycleSpecificationUpdate billingCycleSpecification) throws ApiException {
        com.squareup.okhttp.Call call = patchBillingCycleSpecificationValidateBeforeCall(id, billingCycleSpecification, null, null);
        Type localVarReturnType = new TypeToken<BillingCycleSpecification>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Updates partially a BillingCycleSpecification (asynchronously)
     * This operation updates partially a BillingCycleSpecification entity.
     * @param id Identifier of the BillingCycleSpecification (required)
     * @param billingCycleSpecification The BillingCycleSpecification to be updated (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call patchBillingCycleSpecificationAsync(String id, BillingCycleSpecificationUpdate billingCycleSpecification, final ApiCallback<BillingCycleSpecification> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = patchBillingCycleSpecificationValidateBeforeCall(id, billingCycleSpecification, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<BillingCycleSpecification>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for retrieveBillingCycleSpecification
     * @param id Identifier of the BillingCycleSpecification (required)
     * @param fields Comma-separated properties to provide in response (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call retrieveBillingCycleSpecificationCall(String id, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/billingCycleSpecification/{id}"
            .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(id.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (fields != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("fields", fields));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json;charset=utf-8"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            "application/json;charset=utf-8"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call retrieveBillingCycleSpecificationValidateBeforeCall(String id, String fields, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'id' is set
        if (id == null) {
            throw new ApiException("Missing the required parameter 'id' when calling retrieveBillingCycleSpecification(Async)");
        }
        

        com.squareup.okhttp.Call call = retrieveBillingCycleSpecificationCall(id, fields, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Retrieves a BillingCycleSpecification by ID
     * This operation retrieves a BillingCycleSpecification entity. Attribute selection is enabled for all first level attributes.
     * @param id Identifier of the BillingCycleSpecification (required)
     * @param fields Comma-separated properties to provide in response (optional)
     * @return BillingCycleSpecification
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public BillingCycleSpecification retrieveBillingCycleSpecification(String id, String fields) throws ApiException {
        ApiResponse<BillingCycleSpecification> resp = retrieveBillingCycleSpecificationWithHttpInfo(id, fields);
        return resp.getData();
    }

    /**
     * Retrieves a BillingCycleSpecification by ID
     * This operation retrieves a BillingCycleSpecification entity. Attribute selection is enabled for all first level attributes.
     * @param id Identifier of the BillingCycleSpecification (required)
     * @param fields Comma-separated properties to provide in response (optional)
     * @return ApiResponse&lt;BillingCycleSpecification&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<BillingCycleSpecification> retrieveBillingCycleSpecificationWithHttpInfo(String id, String fields) throws ApiException {
        com.squareup.okhttp.Call call = retrieveBillingCycleSpecificationValidateBeforeCall(id, fields, null, null);
        Type localVarReturnType = new TypeToken<BillingCycleSpecification>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Retrieves a BillingCycleSpecification by ID (asynchronously)
     * This operation retrieves a BillingCycleSpecification entity. Attribute selection is enabled for all first level attributes.
     * @param id Identifier of the BillingCycleSpecification (required)
     * @param fields Comma-separated properties to provide in response (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call retrieveBillingCycleSpecificationAsync(String id, String fields, final ApiCallback<BillingCycleSpecification> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = retrieveBillingCycleSpecificationValidateBeforeCall(id, fields, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<BillingCycleSpecification>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
