/*
 * Account Management
 * This is Swagger UI environment generated for the TMF Account Management specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BillFormatRefOrValue;
import io.swagger.client.model.BillPresentationMediaRefOrValue;
import io.swagger.client.model.BillingCycleSpecificationRefOrValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * The structure of the bill for party accounts (billing or settlement).
 */
@ApiModel(description = "The structure of the bill for party accounts (billing or settlement).")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-19T02:51:28.145Z")
public class BillStructure {
  @SerializedName("cycleSpecification")
  private BillingCycleSpecificationRefOrValue cycleSpecification = null;

  @SerializedName("format")
  private BillFormatRefOrValue format = null;

  @SerializedName("presentationMedia")
  private List<BillPresentationMediaRefOrValue> presentationMedia = null;

  @SerializedName("@baseType")
  private String baseType = null;

  @SerializedName("@schemaLocation")
  private String schemaLocation = null;

  @SerializedName("@type")
  private String type = null;

  public BillStructure cycleSpecification(BillingCycleSpecificationRefOrValue cycleSpecification) {
    this.cycleSpecification = cycleSpecification;
    return this;
  }

   /**
   * Get cycleSpecification
   * @return cycleSpecification
  **/
  @ApiModelProperty(value = "")
  public BillingCycleSpecificationRefOrValue getCycleSpecification() {
    return cycleSpecification;
  }

  public void setCycleSpecification(BillingCycleSpecificationRefOrValue cycleSpecification) {
    this.cycleSpecification = cycleSpecification;
  }

  public BillStructure format(BillFormatRefOrValue format) {
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @ApiModelProperty(value = "")
  public BillFormatRefOrValue getFormat() {
    return format;
  }

  public void setFormat(BillFormatRefOrValue format) {
    this.format = format;
  }

  public BillStructure presentationMedia(List<BillPresentationMediaRefOrValue> presentationMedia) {
    this.presentationMedia = presentationMedia;
    return this;
  }

  public BillStructure addPresentationMediaItem(BillPresentationMediaRefOrValue presentationMediaItem) {
    if (this.presentationMedia == null) {
      this.presentationMedia = new ArrayList<BillPresentationMediaRefOrValue>();
    }
    this.presentationMedia.add(presentationMediaItem);
    return this;
  }

   /**
   * Get presentationMedia
   * @return presentationMedia
  **/
  @ApiModelProperty(value = "")
  public List<BillPresentationMediaRefOrValue> getPresentationMedia() {
    return presentationMedia;
  }

  public void setPresentationMedia(List<BillPresentationMediaRefOrValue> presentationMedia) {
    this.presentationMedia = presentationMedia;
  }

  public BillStructure baseType(String baseType) {
    this.baseType = baseType;
    return this;
  }

   /**
   * When sub-classing, this defines the super-class
   * @return baseType
  **/
  @ApiModelProperty(value = "When sub-classing, this defines the super-class")
  public String getBaseType() {
    return baseType;
  }

  public void setBaseType(String baseType) {
    this.baseType = baseType;
  }

  public BillStructure schemaLocation(String schemaLocation) {
    this.schemaLocation = schemaLocation;
    return this;
  }

   /**
   * A URI to a JSON-Schema file that defines additional attributes and relationships
   * @return schemaLocation
  **/
  @ApiModelProperty(value = "A URI to a JSON-Schema file that defines additional attributes and relationships")
  public String getSchemaLocation() {
    return schemaLocation;
  }

  public void setSchemaLocation(String schemaLocation) {
    this.schemaLocation = schemaLocation;
  }

  public BillStructure type(String type) {
    this.type = type;
    return this;
  }

   /**
   * When sub-classing, this defines the sub-class entity name
   * @return type
  **/
  @ApiModelProperty(value = "When sub-classing, this defines the sub-class entity name")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillStructure billStructure = (BillStructure) o;
    return Objects.equals(this.cycleSpecification, billStructure.cycleSpecification) &&
        Objects.equals(this.format, billStructure.format) &&
        Objects.equals(this.presentationMedia, billStructure.presentationMedia) &&
        Objects.equals(this.baseType, billStructure.baseType) &&
        Objects.equals(this.schemaLocation, billStructure.schemaLocation) &&
        Objects.equals(this.type, billStructure.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cycleSpecification, format, presentationMedia, baseType, schemaLocation, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillStructure {\n");
    
    sb.append("    cycleSpecification: ").append(toIndentedString(cycleSpecification)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    presentationMedia: ").append(toIndentedString(presentationMedia)).append("\n");
    sb.append("    baseType: ").append(toIndentedString(baseType)).append("\n");
    sb.append("    schemaLocation: ").append(toIndentedString(schemaLocation)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

